- name: installing nginx
  hosts: web
  become: yes
  tasks:
  - name: Install nginx
    ansible.builtin.package: # heterogenous module that can work for all distribution
      name: nginx
      state: present
  - name: run nginx
    ansible.builtin.service: 
      name: nginx
      state: started
      enabled: yes