- name: installing nginx
  hosts: web
  become: yes
  tasks:
  - name: Install nginx
    ansible.builtin.package: # heterogenous module that can work for all distribution ex: we use dnf for redhad , apt for ubuntu or Debian
      name: nginx
      state: remove
  # - name: run nginx
  #   ansible.builtin.service: 
  #     name: nginx
  #     state: started
  #     enabled: yes