- name: variable to print
  hosts: web
  vars_files:
  - vars.yaml
  tasks:
  - name: print the informtion
    ansible.builtin.debug:
      msg: "hi,iam learning {{ COURSE }}, duration is {{ DURATION }}"