- name: variable to print
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: please enter the course name
  - name: DURATION
    prompt: please enter the duration
  tasks:
  - name: print the informtion
    ansible.builtin.debug:
      msg: "hi,iam learning {{ COURSE }}, duration is {{ DURATION }}"