- name: variable to print
  hosts: web
  tasks:
  - name: print the informtion
    ansible.builtin.debug:
      msg: "hi, {{NAME}} ...... {{ GREETING }} !" # passing variables in arguments with <file name> -e "NAME=RAMESG GREETING=GOOD MORNING"