- name: create user
  hosts: web
  become: yes
  tasks:
  - name: check is the use is exist or not
    ansible.builtin.command: id expense
    register: USER # HERE USER is a variable that gets outpiut from above command
    ignore_errors: true
  
  - name: print the user information
    ansible.builtin.debug: 
      msg: "user info- {{USER}}"

  - name: create user
    ansible.builtin.command: useradd expense 
    when: USER.rc != 0